name: 'Workflow of Child REPO'

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

env:
  BRANCH_NAME: ${{ github.ref }}

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: |
          echo  "Branch : ${{ env.BRANCH_NAME }}"
         
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Child REPO"
          sleep 120s

