name: 'Workflow of Child REPO'

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

env:
  BRANCH_NAME: ${{ github.ref }}

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Running on a pull request branch.
        if: steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "Running on pr: ${{ steps.branch-name.outputs.current_branch }}"
         
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Child REPO"
          sleep 120s

