name: 'Workflow of Child REPO'

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]

env:
  BRANCH_NAME: ${{ github.ref }}

jobs: 
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        id: branch_name
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | sed 's/refs\/heads\///')"

      - name: Display branch name
        run: echo "Branch name is ${{ steps.branch_name.outputs.branch }}"
         
      - name: Echo Workflow name
        shell: bash
        run: |
          echo "I am Workflow of Child REPO"
          sleep 120s

